title: Niels Doorn, Ph.D. student
description: My research projects on improving software testing education in computer science programs.
theme: jekyll-theme-minimal
show_downloads: false
show_excerpts: false
author: Niels Doorn
logo: logo.jpg
minima:
  social_links:
    twitter: nielsdoorn
    github: nielsdoorn
github:
  is_project_page: false
  is_user_page: false