title: Niels Doorn, Ph.D. student
description: My research projects on improving software testing education in computer science programs.
# theme: jekyll-theme-minimal
show_downloads: false
show_excerpts: false
author: Niels Doorn
logo: logo.jpg
minima:
  social_links:
    twitter: nielsdoorn
    github: nielsdoorn
github:
  is_project_page: false
  is_user_page: false


# remote_theme: pages-themes/leap-day@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

# remote_theme: pages-themes/minimal@v0.2.0

remote_theme: alshedivat/al-folio 

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

