title: Niels Doorn, Ph.D. student
description: My research on improving teaching and learning strategies of software testing in computer science education.
# theme: jekyll-theme-minimal
show_downloads: false
show_excerpts: false
author: Niels Doorn
logo: logo.jpg
github:
  is_project_page: false
  is_user_page: false

remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed
